export type WebsiteLocale = "zh" | "en";

export const GITHUB_REPO = "7836246/kcode";
export const GITHUB_URL = `https://github.com/${GITHUB_REPO}`;
export const GITHUB_RELEASES_URL = `${GITHUB_URL}/releases`;
export const GITHUB_LATEST_RELEASE_URL = `${GITHUB_RELEASES_URL}/latest`;
export const UPSTREAM_URL = "https://github.com/zai-org/ZCode";
export const SITE_ORIGIN = "https://kcode.wiki";

export const websiteCopy = {
  zh: {
    documentTitle: "KCode",
    seoTitle: "KCode | 开源 AI 编程工作台",
    seoDescription:
      "KCode 是开源 AI 编程工作台。自行配置模型供应商，在桌面、浏览器和终端里用 Agent 完成编码与长任务。Apache-2.0，安装包从 GitHub Releases 提供。",
    seoKeywords: "KCode,AI编程,开源Agent,GitHub Releases,自己的模型,桌面端,远程控制",
    brand: "KCODE",
    navDownload: "下载",
    navSource: "源码",
    navDocs: "文档",
    navChangelog: "更新日志",
    navMenu: "打开菜单",
    languageName: "EN",
    themeToLight: "切换到日间模式",
    themeToDark: "切换到夜间模式",
    docsMissingTitle: "没有这一页",
    docsMissingBody: "文档目录里没有这个地址。从侧栏挑一篇即可。",
    changelogTitle: "版本发布与更新",
    changelogLead: "KCode 各版本的更新说明。安装包仍从 GitHub Releases 下载。",
    changelogEmpty: "还没有读到发布记录。",
    changelogGithub: "在 GitHub 查看",
    changelogEnd: "已经到底了，以上就是全部版本记录。",
    changelogRelease: "Release",
    banner: "开源 Apache-2.0 · 上游来自 ZCode · 自行配置供应商",
    headline: "简单、迅捷、自己掌控。",
    subtitle:
      "KCode 是开源 AI 编程工作台。自行配置模型供应商，在桌面、浏览器和终端里完成复杂任务。",
    download: "立即下载 KCode",
    viewAllDownloads: "查看全部下载",
    downloadFallback: "在 GitHub 查看安装包",
    featuresEyebrow: "产品能力",
    featuresTitle: "保持在技术前沿",
    featuresLead: "无论是理清遗留系统还是交付实时特性，KCode 都能让团队保持高效和稳健。",
    features: [
      {
        image: "/images/img-goal@2x.png",
        title: "长程任务",
        body: "用 Goal 管理复杂目标，持续规划、执行与验证，让多步骤工作稳步推进。",
      },
      {
        image: "/images/img-bot@2x.png",
        title: "Bot 控制",
        body: "通过微信、飞书或 Telegram 远程唤起 KCode，让任务随时进入执行状态。",
      },
      {
        image: "/images/img-glm53@2x.png",
        title: "自己的模型",
        body: "自行接入模型供应商。不提供官方登录或套餐，在设置里接上即可开始。",
      },
    ],
    downloadsTitle: "全部下载",
    downloadsLead: "KCode 支持的所有平台安装包",
    mac: "macOS",
    windows: "Windows",
    linux: "Linux",
    linuxBeta: "Beta",
    macApple: "macOS（Apple 芯片）",
    macIntel: "macOS（Intel 芯片）",
    winX64: "Windows（64 位）",
    winArm: "Windows (ARM64)",
    linuxX64: "Linux x64",
    linuxArm: "Linux ARM64",
    extDmg: ".dmg",
    extExe: ".exe",
    footerCopy: "© 2026 KCode",
    footerLicense: "Apache-2.0。源码来自上游 ZCode。",
    footerDisclaimer: "仅供学习参考。",
    footerSource: "GitHub",
    footerUpstream: "上游 ZCode",
    footerNotice: "NOTICE",
  },
  en: {
    documentTitle: "KCode",
    seoTitle: "KCode | Open-source AI coding workbench",
    seoDescription:
      "Bring your own model provider. Run agents on desktop, in the browser, or the terminal. Apache-2.0 installers live on GitHub Releases.",
    seoKeywords: "KCode,AI coding,open source agent,GitHub Releases,BYO provider,desktop,remote control",
    brand: "KCODE",
    navDownload: "Download",
    navSource: "Source",
    navDocs: "Docs",
    navChangelog: "Changelog",
    navMenu: "Open menu",
    languageName: "中文",
    themeToLight: "Switch to light mode",
    themeToDark: "Switch to dark mode",
    docsMissingTitle: "Page not found",
    docsMissingBody: "That docs path is not in the sidebar. Pick another article.",
    changelogTitle: "Releases",
    changelogLead: "What changed in each KCode version. Installers stay on GitHub Releases.",
    changelogEmpty: "No release notes loaded.",
    changelogGithub: "View on GitHub",
    changelogEnd: "That's the full version history.",
    changelogRelease: "Release",
    banner: "Open source Apache-2.0 · Forked from ZCode · Bring your own provider",
    headline: "Simple, fast, and yours.",
    subtitle:
      "KCode is an open-source AI coding workbench. Configure your own model provider and work from desktop, browser, or the terminal.",
    download: "Download KCode",
    viewAllDownloads: "View all downloads",
    downloadFallback: "See installers on GitHub",
    featuresEyebrow: "Capabilities",
    featuresTitle: "Stay at the frontier",
    featuresLead:
      "Whether you are untangling a legacy system or shipping a live feature, KCode keeps the team moving.",
    features: [
      {
        image: "/images/img-goal@2x.png",
        title: "Long-running goals",
        body: "Use Goal to plan, execute, and verify multi-step work.",
      },
      {
        image: "/images/img-bot@2x.png",
        title: "Bot control",
        body: "Wake KCode from WeChat, Feishu, or Telegram and keep tasks running.",
      },
      {
        image: "/images/img-glm53@2x.png",
        title: "Your models",
        body: "Bring your own provider. No official login or plan.",
      },
    ],
    downloadsTitle: "All downloads",
    downloadsLead: "Every installer KCode supports",
    mac: "macOS",
    windows: "Windows",
    linux: "Linux",
    linuxBeta: "Beta",
    macApple: "macOS (Apple silicon)",
    macIntel: "macOS (Intel)",
    winX64: "Windows (x64)",
    winArm: "Windows (ARM64)",
    linuxX64: "Linux x64",
    linuxArm: "Linux ARM64",
    extDmg: ".dmg",
    extExe: ".exe",
    footerCopy: "© 2026 KCode",
    footerLicense: "Apache-2.0. Source comes from upstream ZCode.",
    footerDisclaimer: "For learning and reference only.",
    footerSource: "GitHub",
    footerUpstream: "Upstream ZCode",
    footerNotice: "NOTICE",
  },
} as const;
